# Generated by Django 4.0.5 on 2023-03-31 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticiones.area')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticiones.equipo')),
            ],
            options={
                'verbose_name': 'Problema',
                'verbose_name_plural': 'Problemas',
            },
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En espera', 'En espera'), ('Realizada', 'Realizado')], default='Pendiente', max_length=20)),
                ('fsolicitud', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peticiones.area')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peticiones.equipo')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peticiones.personal')),
                ('problema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peticiones.problema')),
            ],
            options={
                'verbose_name': 'Peticion',
                'verbose_name_plural': 'Peticiones',
            },
        ),
    ]
