# Generated by Django 4.0.5 on 2023-04-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Realizada', 'Realizado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20),
        ),
    ]
