# Generated by Django 4.0.5 on 2023-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0002_alter_peticion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('ncontrol', models.TextField()),
                ('accion', models.TextField(choices=[('Crear Correo', 'Crear Correo'), ('Recuperar Contraseña', 'Recuperar Contraseña')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud Correo',
                'verbose_name_plural': 'Solicitudes Correos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('En Proceso', 'En Proceso')], default='Pendiente', max_length=20),
        ),
    ]
