# Generated by Django 4.0.5 on 2023-04-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0003_correos_alter_peticion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='correos',
            name='accion',
            field=models.TextField(choices=[('Recuperar Contraseña', 'Recuperar Contraseña'), ('Crear Correo', 'Crear Correo')]),
        ),
        migrations.AlterField(
            model_name='correos',
            name='ncontrol',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='correos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
