# Generated by Django 4.0.5 on 2023-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0004_correos_imagen_alter_correos_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correos',
            name='accion',
            field=models.CharField(choices=[('Crear Correo', 'Crear Correo'), ('Recuperar Contraseña', 'Recuperar Contraseña')], max_length=20),
        ),
    ]
